//
//  RegisterInteractor.swift
//  ChatRealtime
//
//  Created Dang Hung on 10/29/18.
//  Copyright © 2018 Dang Hung. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterInteractor: RegisterInteractorInputProtocol {

    weak var presenter: RegisterInteractorOutputProtocol?
}
