//
//  AccountRouter.swift
//  BaseProject
//
//  Created HUNGND on 2/10/19.
//  Copyright © 2019 HUNGND. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AccountRouter: AccountWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AccountViewController(nibName: nil, bundle: nil)
        let interactor = AccountInteractor()
        let router = AccountRouter()
        let presenter = AccountPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
