//
//  AccountProtocols.swift
//  BaseProject
//
//  Created HUNGND on 2/10/19.
//  Copyright © 2019 HUNGND. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AccountWireframeProtocol: class {

}
//MARK: Presenter -
protocol AccountPresenterProtocol: class {

    var interactor: AccountInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol AccountInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol AccountInteractorInputProtocol: class {

    var presenter: AccountInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol AccountViewProtocol: class {

    var presenter: AccountPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
