//
//  AccountViewController.swift
//  BaseProject
//
//  Created HUNGND on 2/10/19.
//  Copyright © 2019 HUNGND. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AccountViewController: UIViewController, AccountViewProtocol {

	var presenter: AccountPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
