//
//  AuthenticatorRouter.swift
//  ChatRealtime
//
//  Created Dang Hung on 10/29/18.
//  Copyright © 2018 Dang Hung. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AuthenticatorRouter: AuthenticatorWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AuthenticatorViewController(nibName: nil, bundle: nil)
        let interactor = AuthenticatorInteractor()
        let router = AuthenticatorRouter()
        let presenter = AuthenticatorPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        return view
    }
    
    func pushToSignIn() {
        let vc = SignInRouter.createModule()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
