//
//  AuthenticatorPresenter.swift
//  ChatRealtime
//
//  Created Dang Hung on 10/29/18.
//  Copyright © 2018 Dang Hung. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AuthenticatorPresenter: AuthenticatorPresenterProtocol{

    weak private var view: AuthenticatorViewProtocol?
    var interactor: AuthenticatorInteractorInputProtocol?
    private let router: AuthenticatorWireframeProtocol

    init(interface: AuthenticatorViewProtocol, interactor: AuthenticatorInteractorInputProtocol?, router: AuthenticatorWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension AuthenticatorPresenter:AuthenticatorInteractorOutputProtocol{
    func pushToLogin() {
        self.router.pushToSignIn()
    }
}
