//
//  SignInPresenter.swift
//  ChatRealtime
//
//  Created Dang Hung on 10/29/18.
//  Copyright © 2018 Dang Hung. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignInPresenter: SignInPresenterProtocol, SignInInteractorOutputProtocol {

    weak private var view: SignInViewProtocol?
    var interactor: SignInInteractorInputProtocol?
    private let router: SignInWireframeProtocol

    init(interface: SignInViewProtocol, interactor: SignInInteractorInputProtocol?, router: SignInWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
